name: CI
on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: ./ec-sri-invoice-signer
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.19.0'
      - run: sudo timedatectl set-timezone America/Guayaquil # date getter function tests are dependent on timezone
      - run: npm ci
      - run: npm run build
      - run: npm run test